import Foundation

/// Exports a PointCloud to a PLY file (ASCII format).
struct PLYExporter {

    /// Write cloud to a temp file and return its URL.
    static func export(_ cloud: PointCloud) throws -> URL {
        let points = cloud.points
        guard !points.isEmpty else {
            throw ExportError.emptyCloud
        }

        var lines: [String] = []
        // PLY header
        lines.append("ply")
        lines.append("format ascii 1.0")
        lines.append("comment Generated by XFeat3D")
        lines.append("element vertex \(points.count)")
        lines.append("property float x")
        lines.append("property float y")
        lines.append("property float z")
        lines.append("property uchar red")
        lines.append("property uchar green")
        lines.append("property uchar blue")
        lines.append("property float confidence")
        lines.append("end_header")

        // Data rows
        for p in points {
            let r = UInt8(max(0, min(255, p.color.x * 255)))
            let g = UInt8(max(0, min(255, p.color.y * 255)))
            let b = UInt8(max(0, min(255, p.color.z * 255)))
            lines.append("\(p.position.x) \(p.position.y) \(p.position.z) \(r) \(g) \(b) \(p.confidence)")
        }

        let content = lines.joined(separator: "\n") + "\n"

        let dir = FileManager.default.temporaryDirectory
        let url = dir.appendingPathComponent("pointcloud_\(Int(Date().timeIntervalSince1970)).ply")
        try content.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    enum ExportError: Error, LocalizedError {
        case emptyCloud
        var errorDescription: String? {
            switch self {
            case .emptyCloud: return "Point cloud is empty — scan the environment first."
            }
        }
    }
}
